export { default as About } from "./About/About";
export { default as Courses } from "./Courses/Courses";
export { default as Experience } from "./Experience/Experience";
export { default as Footer } from "./Footer/Footer";
export { default as Header } from "./Header/Header";
export { default as HardSkills } from "./HardSkills/HardSkills";
export { default as SoftSkills } from "./SoftSkills/SoftSkills";
export { default as Testimonials } from "./Testimonials/Testimonials";
export { default as Work } from "./Work/Work";
